# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OAQ Publisher Workflow Docs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  **Welcome to OAQ!** OAQ is a web-based tool that helps publishers
  create author questionnaires and creates structured data from
  author responses. In future developments, it will also
  facilitate sharing that data with libraries to allow us to
  create rich discovery metadata earlier in the publication
  process, and to make authors more discoverable.

  You can read more about the project on the
  [Harvard Library portal](http://library.harvard.edu/oaq).

  {:toc}

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
theme: minima

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
